#!/usr/bin/env python3
"""
E1 detailed report generator — writes rebuttal_exp/E1.exp.md from the two
CSVs (out/E1/{family}_metrics.csv + the paper's quantization CSV). Every
table in E1.exp.md is regenerated by this script; never hand-edit numbers.

Covers: both bound gauges (B_I identity / B_W Procrustes — App C.1 family),
both similarity gauges (Omega_I / Omega_W, full-feature) against the
re-extracted baselines (CKA / SVCCA / Procrustes distance), the component-
level mechanism table (gamma_W / Shape / Scale as rankers), the gsm8k
full-vs-subsample artifact evidence, head-protocol subgroups, and bootstrap
CIs. Zero GPU, stdlib only.

Usage: python3 rebuttal_exp/exp_e1_report.py
"""

from __future__ import annotations

import csv
import math
import random
import statistics
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
OUT = HERE / "E1.exp.md"
QCSV = REPO / "exp_result" / "quantization" / "quantization_merged_slim.csv"

BENCH = ["arc", "mmlu", "squad", "triviaqa", "gsm8k"]
FAM_ID = {"llama": "meta-llama/Meta-Llama-3.1-8B",
          "qwen": "Qwen/Qwen3-8B-Base"}
GGUF = {"Q8_0", "Q6_K", "Q5_K_M", "Q4_K_M", "Q3_K_M", "Q2_K"}


def rankdata(v):
    o = sorted(range(len(v)), key=lambda i: v[i])
    r = [0.0] * len(v)
    i = 0
    while i < len(o):
        j = i + 1
        while j < len(o) and v[o[j]] == v[o[i]]:
            j += 1
        for k in range(i, j):
            r[o[k]] = (i + j + 1) / 2
        i = j
    return r


def rs(x, y):
    if len(x) < 3:
        return float("nan")
    rx, ry = rankdata(x), rankdata(y)
    mx, my = statistics.mean(rx), statistics.mean(ry)
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    den = math.sqrt(sum((a - mx) ** 2 for a in rx)
                    * sum((b - my) ** 2 for b in ry))
    return num / den if den > 0 else float("nan")


def load(fam):
    paper = {}
    for r in csv.DictReader(open(QCSV)):
        if r["target_model"] != FAM_ID[fam]:
            continue
        try:
            paper[(r["Label"], r["dataset"])] = {
                "B_I": float(r["Bound_I"]), "B_W": float(r["Bound_W"]),
                "O_I": float(r["Omega_I"]), "O_W": float(r["Omega_W"]),
                "g_W": float(r["gamma_W"]), "g_I": float(r["gamma_I"]),
                "Sh_I": float(r["Shape_I"]), "Sh_W": float(r["Shape_W"]),
                "Sc": float(r["Scale"]),
            }
        except ValueError:
            pass
    rows = list(csv.DictReader(open(HERE / "out" / "E1"
                                    / f"{fam}_metrics.csv")))
    return paper, rows


def bench_scores(paper, rows, b):
    sub = [r for r in rows if r["dataset"] == b
           and not math.isnan(float(r["|MdR|"]))]
    dr = [float(r["|MdR|"]) for r in sub]
    P = [paper[(r["label"], b)] for r in sub]
    return sub, dr, P


def main():
    rng = random.Random(0)
    L = ["# E1.exp — 完整明細表(自動生成,勿手改;來源 = out/E1/*_metrics.csv"
         " + 論文 quantization CSV)",
         "",
         "重生指令:`python3 rebuttal_exp/exp_e1_report.py`。",
         "",
         "## 0. 欄位出處與不變性等級",
         "",
         "| 欄位 | 特徵來源 | 不變性 | certified? |",
         "|---|---|---|---|",
         "| B_I(=Bound_I) | 論文 CSV,全量 | 座標敏感(W=I gauge) | ✅ Thm 1 |",
         "| B_W(=Bound_W) | 論文 CSV,全量 | **旋轉不變**(W=W_N gauge) | ✅ Thm 1(App C.1) |",
         "| 1-Ω_I / 1-Ω_W(full) | 論文 CSV,全量(paper pipeline) | 座標敏感 / 旋轉不變 | ✗(相似度) |",
         "| 1-CKA / 1-SVCCA / Procr(pod) | 重抽特徵(cap 65536,gsm8k 已全量 REDO) | 旋轉不變 | ✗ |",
         "| 1-Ω_I(pod) / 1-Ω_W(pod) | 重抽特徵(同上;OWp=nuclear,與 CKA/Procr 同一份特徵) | 座標敏感 / 旋轉不變 | ✗ |",
         ""]

    KEYS = ("B_I", "B_W", "OIf", "OWf", "CK", "SV", "PR", "OIp", "OWp")
    data = {}
    for fam in ("llama", "qwen"):
        paper, rows = load(fam)
        cols = {k: [] for k in KEYS}
        ns = []
        for b in BENCH:
            sub, dr, P = bench_scores(paper, rows, b)
            v = {
                "B_I": rs([p["B_I"] for p in P], dr),
                "B_W": rs([p["B_W"] for p in P], dr),
                "OIf": rs([1 - p["O_I"] for p in P], dr),
                "OWf": rs([1 - p["O_W"] for p in P], dr),
                "CK": rs([1 - float(r["cka"]) for r in sub], dr),
                "SV": rs([1 - float(r["svcca"]) for r in sub], dr),
                "PR": rs([float(r["procr_dist"]) for r in sub], dr),
                "OIp": rs([1 - float(r["omega_I"]) for r in sub], dr),
                # E1-native shape core (nuclear Omega_W on re-extracted
                # features). NaN if the CSV predates the 2026-07-26 column.
                "OWp": rs([1 - float(r.get("omega_W", "nan"))
                           for r in sub], dr),
            }
            for k in KEYS:
                cols[k].append(v[k])
            ns.append(len(sub))
        data[fam] = (paper, rows, cols, ns)

    # ── §1: combined main table, BOTH families in one block ────────────
    L += ["## 1. 主表(llama + qwen 合併):rs(score, |dR|)",
          "",
          "| family | bench | n | B_I | B_W | 1-Ω_I full | 1-Ω_W full "
          "| 1-CKA | 1-SVCCA | Procr | 1-Ω_I pod | 1-Ω_W pod |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for fam in ("llama", "qwen"):
        _, _, cols, ns = data[fam]
        for i, b in enumerate(BENCH):
            L.append(f"| {fam} | {b} | {ns[i]} | " + " | ".join(
                f"{cols[k][i]:+.3f}" for k in KEYS) + " |")
        for tag, sl in (("mean(5)", slice(None)), ("ex-gsm8k", slice(0, 4))):
            L.append(f"| {fam} | **{tag}** | | " + " | ".join(
                f"**{statistics.mean(cols[k][sl]):+.3f}**" for k in KEYS)
                + " |")
    L.append("")

    for fam in ("llama", "qwen"):
        paper, rows, cols, ns = data[fam]
        n_var = len({r["label"] for r in rows})
        L += [f"## {fam} 明細(n={n_var} variants,GPTQ 全補齊)", ""]

        # component mechanism table
        L += ["### 2. 成分機制表:家族內部誰在攜帶排序訊號",
              "",
              "恆等式:procr_dist² = Scale + Shape_W = δ_W²——E1 的 Procrustes"
              " baseline 就是 bound 家族自己的 feature 臂(B_W = K_feat·δ_W"
              " + K_pred·γ_W);1-Ω_W 則是把 Scale 正規化掉的純形狀核。",
              "",
              "| bench | γ_W | δ_W(=√(Sc+Sh_W)) | Shape_W | Shape_I | Scale |",
              "|---|---|---|---|---|---|"]
        for b in BENCH:
            sub, dr, P = bench_scores(paper, rows, b)
            L.append(f"| {b} | "
                     f"{rs([p['g_W'] for p in P], dr):+.3f} | "
                     f"{rs([math.sqrt(p['Sc'] + p['Sh_W']) for p in P], dr):+.3f} | "
                     f"{rs([p['Sh_W'] for p in P], dr):+.3f} | "
                     f"{rs([p['Sh_I'] for p in P], dr):+.3f} | "
                     f"{rs([p['Sc'] for p in P], dr):+.3f} |")
        L.append("")

        # gsm8k: paper pipeline vs E1 re-extraction (full-cap REDO)
        sub, dr, P = bench_scores(paper, rows, "gsm8k")
        n_gsm = sub[0]["n_tokens"] if sub else "?"
        owp = rs([1 - float(r.get("omega_W", "nan")) for r in sub], dr)
        L += ["### 3. gsm8k:paper pipeline vs 重抽特徵(2026-07-26 全量 REDO)",
              "",
              f"重抽 gsm8k 已用 cap 65536,實得 n_tokens={n_gsm}(全量,非 16k "
              "子抽樣)。因此「paper full vs pod」的差距若仍在,就**不是**子抽樣 "
              "artifact,而是 paper 與 E1 兩條抽特徵管線的差異。",
              "",
              "| 量 | paper full | pod(重抽,全量) |",
              "|---|---|---|",
              f"| 1-Ω_I | {rs([1 - p['O_I'] for p in P], dr):+.3f} "
              f"| {rs([1 - float(r['omega_I']) for r in sub], dr):+.3f} |",
              f"| 1-Ω_W(shape core) | {rs([1 - p['O_W'] for p in P], dr):+.3f} "
              f"| {owp:+.3f} |",
              f"| 1-CKA | (n/a paper) | {rs([1 - float(r['cka']) for r in sub], dr):+.3f} |",
              f"| B_W(=Bound_W) | {rs([p['B_W'] for p in P], dr):+.3f} | (joined) |",
              "",
              "判讀:pod 的 1-Ω_W 是在**與 CKA/Procr 同一份重抽特徵**上算的 nuclear "
              "shape core(draft 的 Omega_N)。若 pod 1-Ω_W ≈ pod 1-Ω_I ≈ 1-CKA "
              "(皆高),則 gsm8k 的 shape core 在重抽管線上**不飽和**,draft "
              "「Omega_N +0.48 saturates」與「machinery buys +0.088」需改寫成 "
              "paper-pipeline 專屬敘述;若 pod 1-Ω_W 明顯低於 1-CKA,則 shape "
              "核確有 gsm8k 專屬鬆弛,原敘述可在 pod gauge 下重述。",
              ""]

        # subgroups
        L += ["### 4. Head-協議子群(B_I / B_W / 1-CKA)",
              "", "| bench | ALL | GGUF-only | non-GGUF |", "|---|---|---|---|"]
        for b in BENCH:
            sub, dr, P = bench_scores(paper, rows, b)
            cells = []
            for name, keep in (
                    ("ALL", [True] * len(sub)),
                    ("GGUF", [r["label"].split(" vs ")[-1] in GGUF
                              for r in sub]),
                    ("nonGGUF", [r["label"].split(" vs ")[-1] not in GGUF
                                 for r in sub])):
                idx = [i for i, k in enumerate(keep) if k]
                if len(idx) < 4:
                    cells.append("n<4")
                    continue
                d2 = [dr[i] for i in idx]
                bi = rs([P[i]["B_I"] for i in idx], d2)
                bw = rs([P[i]["B_W"] for i in idx], d2)
                ck = rs([1 - float(sub[i]["cka"]) for i in idx], d2)
                cells.append(f"{bi:+.3f}/{bw:+.3f}/{ck:+.3f} (n={len(idx)})")
            L.append(f"| {b} | " + " | ".join(cells) + " |")
        L.append("")

        # bootstrap
        L += ["### 5. Bootstrap(variants 重抽 5000 reps;B−CKA 差距顯著性)",
              ""]
        cells_d = {}
        for b in BENCH:
            sub, dr, P = bench_scores(paper, rows, b)
            cells_d[b] = [(P[i]["B_I"], P[i]["B_W"],
                           1 - float(sub[i]["cka"]), dr[i])
                          for i in range(len(sub))]

        def mdiff(cd, benches, which):
            ds = []
            for b in benches:
                pts = cd[b]
                d = [p[3] for p in pts]
                ds.append(rs([p[which] for p in pts], d)
                          - rs([p[2] for p in pts], d))
            return statistics.mean(ds)

        for which, nm in ((0, "B_I−CKA"), (1, "B_W−CKA")):
            for tag, benches in (("all-5", BENCH),
                                 ("ex-gsm8k", BENCH[:4])):
                obs = mdiff(cells_d, benches, which)
                boots = sorted(
                    mdiff({b: [cells_d[b][rng.randrange(len(cells_d[b]))]
                               for _ in cells_d[b]] for b in benches},
                          benches, which)
                    for _ in range(5000))
                lo = boots[int(0.025 * len(boots))]
                hi = boots[int(0.975 * len(boots))]
                sig = ("顯著" if hi < 0 or lo > 0
                       else "不顯著(CI 蓋 0)")
                L.append(f"- {nm} {tag}: {obs:+.3f}, "
                         f"95% CI [{lo:+.3f}, {hi:+.3f}] — {sig}")
        L.append("")

    L += ["## 待辦",
          "",
          "- [ ] `REDO=\"gsm8k\"` 重算後重跑本產生器(§3 回填 CKA-full;"
          "§1 的 pod 欄 gsm8k 列轉全量)",
          "- [ ] draft 三處以本檔 §1/§5 定稿(兩-gauge 框架)", ""]
    OUT.write_text("\n".join(L))
    print(f"[written] {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
